name: minimal
description: Minimal example for BLOB/BYTEA postgres fields with Drift.
version: 0.0.42

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  drift: ^2.2.0
  drift_postgres:
    git:
      url: https://github.com/simolus3/drift.git
      path: extras/drift_postgres
  postgres: ^2.5.2

dev_dependencies:
  build_runner: ^2.2.0
  drift_dev: ^2.2.0
  lints: ^2.0.0
  test: ^1.16.0
